const LANG_KEY = "learnmore.lang";

const dictionary = {
  es: {
    "nav.home": "Inicio",
    "nav.guides": "Guias",
    "nav.careers": "Carreras",
    "nav.contact": "Contacto",
    "nav.login": "Entrar",
    "nav.admin": "Admin",
    "nav.profile": "Perfil",
    "nav.reviews": "Reseñas",
    "career.mecatronica": "Mecatrónica",
    "career.ti": "TI e Innovación Digital",
    "career.procesos": "Procesos Industriales",
    "career.general": "General",
    "admin.active": "Activo",
    "admin.local": "Local",
    "admin.recentActivity": "Actividad reciente",
    "admin.activityNone": "Sin actividad reciente.",
    "admin.careerGeneral": "General (todas las carreras)",
    "admin.edit": "Editar",
    "admin.delete": "Eliminar",
    "admin.removeAdmin": "Quitar admin",
    "admin.makeAdmin": "Hacer admin",
    "admin.markRead": "Marcar leído",
    "admin.reply": "Responder",
    "admin.publicSite": "Sitio público",
    "admin.logout": "Cerrar sesión",
    "admin.topTitle": "Panel administrativo",
    "admin.guidesTitle": "Gestión de guías",
    "admin.guidesPublished": "Guías publicadas",
    "admin.careersTitle": "Gestión de carreras",
    "admin.careersRegistered": "Carreras registradas",
    "admin.usersTitle": "Gestión de usuarios",
    "admin.usersRegistered": "Usuarios registrados",
    "admin.popularityTitle": "Popularidad de los Recursos (Visitas)",
    "admin.popularityCopy": "Visualización de las guías más consultadas mediante gráficos de barras estructurados.",
    "guides.featured": "Guías destacadas",
    "guides.popularBadge": "Lo más consultado",
    "guides.popularTitle": "Guías más vistas",
    "guides.popularCopy": "Las guías de aprendizaje más visitadas por la comunidad estudiantil.",
    "profile.myReviews": "Mis reseñas",
    "profile.myMessages": "Mis comentarios",
    "profile.myReviewsBadge": "Mis datos",
    "profile.myMessagesBadge": "Mis datos",
    "profile.noReviews": "No has escrito reseñas todavía.",
    "profile.noMessages": "No has enviado mensajes todavía.",
    "profile.edit": "Editar",
    "profile.delete": "Eliminar",
    "profile.adminReply": "Respuesta del admin:",
    "profile.anonymous": "Anónimo",
    "profile.new": "Nuevo",
    "profile.read": "Leído",
    "profile.replied": "Respondido",
    "profile.confirmDelete": "¿Estás seguro de eliminar este elemento?",
    "profile.enterComment": "Escribe el nuevo comentario:",
    "profile.enterStars": "Calificación (1-5 estrellas):",
    "profile.enterSubject": "Escribe el nuevo asunto:",
    "profile.enterMessage": "Escribe el nuevo mensaje:",
    "profile.errorUpdate": "Error al actualizar:",
    "profile.errorDelete": "Error al eliminar:",
    "profile.photoSizeError": "La imagen debe pesar menos de 1 MB.",
    "profile.photoTypeError": "Selecciona un archivo de imagen.",
    "profile.loginPrompt": "Debes iniciar sesión para acceder a las guías.",
    "reviews.badge": "Opiniones de la comunidad",
    "reviews.title": "Reseñas de usuarios",
    "reviews.copy": "Comparte tu experiencia con LEARNMORE y lee lo que otros estudiantes opinan.",
    "reviews.formTitle": "Escribe tu reseña",
    "reviews.namePlaceholder": "Tu nombre",
    "reviews.rating": "Calificación:",
    "reviews.commentPlaceholder": "Cuéntanos tu experiencia...",
    "reviews.submit": "Publicar reseña",
    "reviews.error": "Por favor completa todos los campos y selecciona una calificación.",
    "reviews.platformTab": "Reseñas de la Plataforma",
    "reviews.guidesTab": "Reseñas de Guías",
    "hero.badge": "Sistema de Guias de Aprendizaje",
    "hero.title": "Aprende mas rapido. Estudia con proposito.",
    "hero.copy": "LEARNMORE centraliza guias, temarios y recursos academicos para que estudiantes y docentes encuentren material actualizado por carrera y semestre.",
    "hero.primary": "Explorar guias",
    "hero.secondary": "Crear cuenta",
    "stats.guides": "Guias",
    "stats.careers": "Carreras",
    "stats.semesters": "Semestres",
    "careers.badge": "Programas academicos",
    "careers.title": "Carreras disponibles",
    "careers.copy": "Filtra el contenido por area academica y encuentra guias organizadas por semestre.",
    "guides.badge": "Material de estudio",
    "guides.title": "Guias academicas",
    "guides.copy": "Contenido dinamico listo para conectarse con Supabase.",
    "guides.empty": "No hay guias con esos filtros.",
    "guides.view": "Ver guía",
    "filters.all": "Todas",
    "filters.semester": "Todos los semestres",
    "contact.badge": "Soporte academico",
    "contact.title": "Contactanos",
    "contact.copy": "Envia dudas, reportes o propuestas de material. El panel administrativo mostrara estos mensajes.",
    "contact.asideTitle": "Estamos para ayudarte",
    "contact.asideCopy": "Incluye tu carrera y semestre para que el equipo pueda responder con mas precision.",
    "form.name": "Nombre",
    "form.email": "Correo",
    "form.career": "Carrera",
    "form.careerPlaceholder": "TI e Innovacion Digital",
    "form.subject": "Asunto",
    "form.message": "Mensaje",
    "form.send": "Enviar mensaje",
    "profile.phonePlaceholder": "222 000 0000",
    "profile.bioPlaceholder": "Agrega notas, intereses o informacion academica",
    "admin.fileUrlPlaceholder": "https://...",
    "admin.keyPlaceholder": "ti",
    "admin.passwordPlaceholder": "Solo para modo local",
    "admin.userSearchPlaceholder": "Nombre o correo",
    "footer.copy": "Sistema de Guias de Aprendizaje. Plataforma academica administrable.",
    "auth.loginBadge": "Acceso seguro",
    "auth.loginTitle": "Iniciar sesion",
    "auth.password": "Contrasena",
    "auth.loginButton": "Entrar",
    "auth.reset": "Recuperar contrasena",
    "auth.newPassword": "Nueva contrasena",
    "auth.updatePasswordButton": "Actualizar contrasena",
    "auth.noAccount": "No tienes cuenta?",
    "auth.registerLink": "Registrate",
    "auth.registerBadge": "Nueva cuenta",
    "auth.registerTitle": "Crear cuenta",
    "auth.registerButton": "Registrarme",
    "auth.hasAccount": "Ya tienes cuenta?",
    "auth.loginLink": "Inicia sesion",
    "auth.backHome": "Volver al inicio",
    "profile.badge": "Cuenta",
    "profile.title": "Mi perfil",
    "profile.phone": "Telefono",
    "profile.semester": "Semestre",
    "profile.cuatrimestre": "Cuatrimestre",
    "profile.studentId": "Matricula",
    "profile.bio": "Informacion personal",
    "profile.photo": "Cambiar foto",
    "profile.save": "Guardar perfil",
    "profile.logout": "Cerrar sesion",
    "profile.delete": "Borrar cuenta",
    "admin.dashboard": "Dashboard",
    "admin.guides": "Guias",
    "admin.guideTitle": "Gestion de guias",
    "admin.guideTitleLabel": "Titulo",
    "admin.guideDescLabel": "Descripcion",
    "admin.guideDetailLabel": "Detalle",
    "admin.guideCareerLabel": "Carrera",
    "admin.guideSemLabel": "Semestre",
    "admin.guideTopicsLabel": "Temas separados por coma",
    "admin.guideFileUrlLabel": "URL de PDF o recurso",
    "admin.guideFileLabel": "Archivo PDF",
    "admin.saveGuide": "Guardar guia",
    "admin.clear": "Limpiar",
    "admin.careers": "Carreras",
    "admin.reviews": "Reseñas",
    "admin.careerTitle": "Gestion de carreras",
    "admin.careerKeyLabel": "Clave",
    "admin.careerNameLabel": "Nombre",
    "admin.careerDescLabel": "Descripcion",
    "admin.careerColorLabel": "Color",
    "admin.saveCareer": "Guardar carrera",
    "admin.messages": "Mensajes",
    "admin.messageTitle": "Mensajes de contacto",
    "admin.users": "Usuarios",
    "admin.userTitle": "Gestion de usuarios",
    "admin.userNameLabel": "Nombre",
    "admin.userEmailLabel": "Correo",
    "admin.userRoleLabel": "Rol",
    "admin.userRoleUser": "Usuario",
    "admin.userRoleAdmin": "Administrador",
    "admin.localPasswordLabel": "Contrasena local",
    "admin.saveUser": "Guardar usuario",
    "admin.registeredUsers": "Usuarios registrados",
    "admin.search": "Buscar",
    "admin.filterAll": "Todos",
    "admin.filterAdmins": "Administradores",
    "admin.filterUsers": "Usuarios",
    "admin.logout": "Cerrar sesion",
    "admin.edit": "Editar",
    "admin.delete": "Eliminar",
    "admin.removeAdmin": "Quitar admin",
    "admin.makeAdmin": "Hacer admin",
    "admin.viewPublished": "Guias publicadas",
    "admin.viewRegistered": "Carreras registradas",
    "admin.replyLabel": "Respuesta:",
    "admin.noMessages": "No hay mensajes.",
    "admin.now": "Ahora",
    "admin.savingGuide": "Guardando guía...",
    "admin.guideSaved": "Guía guardada correctamente.",
    "admin.errorSaveCareer": "Error al guardar carrera:",
    "admin.userSaved": "Usuario guardado correctamente.",
    "admin.errorDelete": "Error al eliminar:",
    "admin.errorDeleteReview": "Error al eliminar reseña:",
    "admin.errorReply": "Error al responder:",
    "admin.writeReplyPrompt": "Escribe tu respuesta:",
    "admin.noUsersFiltered": "No hay usuarios con esos filtros.",
    "admin.replyMessageTitle": "Responder mensaje",
    "admin.replyToLabel": "Responder a",
    "admin.writeReplyPlaceholder": "Escribe tu respuesta...",
    "admin.sendReplyButton": "Enviar respuesta",
    "admin.cancelButton": "Cancelar",
    "career.01": "Mecatrónica",
    "career.02": "TI e Innovación Digital",
    "career.03": "Procesos Industriales",
    "career.00": "General",
    "career.general": "General",
    "mostViewed.badge": "Populares",
    "mostViewed.title": "Más Vistos",
    "mostViewed.copy": "Guias ordenadas por número de vistas.",
    "mostViewed.empty": "No hay guias disponibles.",
  },
  en: {
    "nav.home": "Home",
    "nav.guides": "Guides",
    "nav.careers": "Careers",
    "nav.contact": "Contact",
    "nav.login": "Sign in",
    "nav.admin": "Admin",
    "nav.profile": "Profile",
    "nav.reviews": "Reviews",
    "career.mecatronica": "Mechatronics",
    "career.ti": "IT & Digital Innovation",
    "career.procesos": "Industrial Processes",
    "career.general": "General",
    "admin.active": "Active",
    "admin.local": "Local",
    "admin.recentActivity": "Recent activity",
    "admin.activityNone": "No recent activity.",
    "admin.careerGeneral": "General (all careers)",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.removeAdmin": "Remove admin",
    "admin.makeAdmin": "Make admin",
    "admin.markRead": "Mark read",
    "admin.reply": "Reply",
    "admin.publicSite": "Public site",
    "admin.logout": "Sign out",
    "admin.topTitle": "Administration panel",
    "admin.guidesTitle": "Manage guides",
    "admin.guidesPublished": "Published guides",
    "admin.careersTitle": "Manage careers",
    "admin.careersRegistered": "Registered careers",
    "admin.usersTitle": "Manage users",
    "admin.usersRegistered": "Registered users",
    "admin.popularityTitle": "Resource Popularity (Views)",
    "admin.popularityCopy": "Visualization of the most consulted guides using structured bar charts.",
    "guides.featured": "Featured guides",
    "guides.popularBadge": "Most popular",
    "guides.popularTitle": "Most viewed guides",
    "guides.popularCopy": "The most visited learning guides by the student community.",
    "profile.myReviews": "My reviews",
    "profile.myMessages": "My comments",
    "profile.myReviewsBadge": "My data",
    "profile.myMessagesBadge": "My data",
    "profile.noReviews": "You haven't written any reviews yet.",
    "profile.noMessages": "You haven't sent any messages yet.",
    "profile.edit": "Edit",
    "profile.delete": "Delete",
    "profile.adminReply": "Admin reply:",
    "profile.anonymous": "Anonymous",
    "profile.new": "New",
    "profile.read": "Read",
    "profile.replied": "Replied",
    "profile.confirmDelete": "Are you sure you want to delete this item?",
    "profile.enterComment": "Enter the new comment:",
    "profile.enterStars": "Rating (1-5 stars):",
    "profile.enterSubject": "Enter the new subject:",
    "profile.enterMessage": "Enter the new message:",
    "profile.errorUpdate": "Error updating:",
    "profile.errorDelete": "Error deleting:",
    "profile.photoSizeError": "The image must weigh less than 1 MB.",
    "profile.photoTypeError": "Please select an image file.",
    "profile.loginPrompt": "You must log in to access the guides.",
    "reviews.badge": "Community feedback",
    "reviews.title": "User reviews",
    "reviews.copy": "Share your experience with LEARNMORE and read what other students think.",
    "reviews.formTitle": "Write a review",
    "reviews.namePlaceholder": "Your name",
    "reviews.rating": "Rating:",
    "reviews.commentPlaceholder": "Tell us your experience...",
    "reviews.submit": "Submit review",
    "reviews.error": "Please complete all fields and select a rating.",
    "reviews.platformTab": "Platform Reviews",
    "reviews.guidesTab": "Guide Reviews",
    "hero.badge": "Learning Guides System",
    "hero.title": "Learn faster. Study with purpose.",
    "hero.copy": "LEARNMORE centralizes guides, syllabi and academic resources so students and teachers can find updated material by career and semester.",
    "hero.primary": "Explore guides",
    "hero.secondary": "Create account",
    "stats.guides": "Guides",
    "stats.careers": "Careers",
    "stats.semesters": "Semesters",
    "careers.badge": "Academic programs",
    "careers.title": "Available careers",
    "careers.copy": "Filter content by academic area and find guides organized by semester.",
    "guides.badge": "Study material",
    "guides.title": "Academic guides",
    "guides.copy": "Dynamic content ready to connect with Supabase.",
    "guides.empty": "No guides match those filters.",
    "guides.view": "View Guide",
    "filters.all": "All",
    "filters.semester": "All semesters",
    "contact.badge": "Academic support",
    "contact.title": "Contact us",
    "contact.copy": "Send questions, reports or material proposals. The admin panel will show these messages.",
    "contact.asideTitle": "We are here to help",
    "contact.asideCopy": "Include your career and semester so the team can answer more precisely.",
    "form.name": "Name",
    "form.email": "Email",
    "form.career": "Career",
    "form.careerPlaceholder": "Digital Innovation Engineering",
    "form.subject": "Subject",
    "form.message": "Message",
    "form.send": "Send message",
    "profile.phonePlaceholder": "(222) 000-0000",
    "profile.bioPlaceholder": "Add notes, interests, or academic info",
    "admin.fileUrlPlaceholder": "https://...",
    "admin.keyPlaceholder": "di",
    "admin.passwordPlaceholder": "Local mode only",
    "admin.userSearchPlaceholder": "Name or email",
    "footer.copy": "Learning Guides System. Manageable academic platform.",
    "auth.loginBadge": "Secure access",
    "auth.loginTitle": "Sign in",
    "auth.password": "Password",
    "auth.loginButton": "Sign in",
    "auth.reset": "Reset password",
    "auth.newPassword": "New password",
    "auth.updatePasswordButton": "Update password",
    "auth.noAccount": "No account?",
    "auth.registerLink": "Register",
    "auth.registerBadge": "New account",
    "auth.registerTitle": "Create account",
    "auth.registerButton": "Register",
    "auth.hasAccount": "Already have an account?",
    "auth.loginLink": "Sign in",
    "auth.backHome": "Back home",
    "profile.badge": "Account",
    "profile.title": "My profile",
    "profile.phone": "Phone",
    "profile.semester": "Semester",
    "profile.cuatrimestre": "Semester",
    "profile.studentId": "Student ID",
    "profile.bio": "Personal information",
    "profile.photo": "Change photo",
    "profile.save": "Save profile",
    "profile.logout": "Sign out",
    "profile.delete": "Delete account",
    "admin.dashboard": "Dashboard",
    "admin.guides": "Guides",
    "admin.guideTitle": "Manage guides",
    "admin.guideTitleLabel": "Title",
    "admin.guideDescLabel": "Description",
    "admin.guideDetailLabel": "Detail",
    "admin.guideCareerLabel": "Career",
    "admin.guideSemLabel": "Semester",
    "admin.guideTopicsLabel": "Topics (comma separated)",
    "admin.guideFileUrlLabel": "PDF or resource URL",
    "admin.guideFileLabel": "PDF file",
    "admin.saveGuide": "Save guide",
    "admin.clear": "Clear",
    "admin.careers": "Careers",
    "admin.reviews": "Reviews",
    "admin.careerTitle": "Manage careers",
    "admin.careerKeyLabel": "Key",
    "admin.careerNameLabel": "Name",
    "admin.careerDescLabel": "Description",
    "admin.careerColorLabel": "Color",
    "admin.saveCareer": "Save career",
    "admin.messages": "Messages",
    "admin.messageTitle": "Contact messages",
    "admin.users": "Users",
    "admin.userTitle": "Manage users",
    "admin.userNameLabel": "Name",
    "admin.userEmailLabel": "Email",
    "admin.userRoleLabel": "Role",
    "admin.userRoleUser": "User",
    "admin.userRoleAdmin": "Admin",
    "admin.localPasswordLabel": "Local password",
    "admin.saveUser": "Save user",
    "admin.registeredUsers": "Registered users",
    "admin.search": "Search",
    "admin.filterAll": "All",
    "admin.filterAdmins": "Admins",
    "admin.filterUsers": "Users",
    "admin.logout": "Sign out",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.removeAdmin": "Remove admin",
    "admin.makeAdmin": "Make admin",
    "admin.viewPublished": "Published guides",
    "admin.viewRegistered": "Registered careers",
    "admin.replyLabel": "Reply:",
    "admin.noMessages": "No messages.",
    "admin.now": "Just now",
    "admin.savingGuide": "Saving guide...",
    "admin.guideSaved": "Guide saved successfully.",
    "admin.errorSaveCareer": "Error saving career:",
    "admin.userSaved": "User saved successfully.",
    "admin.errorDelete": "Error deleting:",
    "admin.errorDeleteReview": "Error deleting review:",
    "admin.errorReply": "Error replying:",
    "admin.writeReplyPrompt": "Write your reply:",
    "admin.noUsersFiltered": "No users match those filters.",
    "admin.replyMessageTitle": "Reply Message",
    "admin.replyToLabel": "Reply to",
    "admin.writeReplyPlaceholder": "Write your reply...",
    "admin.sendReplyButton": "Send reply",
    "admin.cancelButton": "Cancel",
    "career.01": "Mechatronics",
    "career.02": "IT & Digital Innovation",
    "career.03": "Industrial Processes",
    "career.00": "General",
    "career.general": "General",
    "mostViewed.badge": "Popular",
    "mostViewed.title": "Most Viewed",
    "mostViewed.copy": "Guides sorted by number of views.",
    "mostViewed.empty": "No guides available.",
    
    // Dynamic Predefined Guides - Titles
    "Planeación de Requerimientos de Materiales": "Material Requirements Planning",
    "Lógica Externa": "External Logic",
    "Desarrollo Web Orientado a Servicios": "Service-Oriented Web Development",
    "Inglés Profesional y Académico": "Professional and Academic English",
    
    // Dynamic Predefined Guides - Descriptions & Details
    "Guía de estudio analítica sobre el procedimiento sistemático para la planificación de componentes de fabricación, traduciendo el Plan Maestro de Producción en necesidades reales de materiales bajo fechas y cantidades exactas.": "Analytical study guide on the systematic procedure for manufacturing component planning, translating the Master Production Schedule into actual material needs under exact dates and quantities.",
    "Guía de estudio orientada a comprender los elementos, reglas de negocio y contextos reales que existen fuera del núcleo técnico de un sistema y que determinan su correcto funcionamiento e interacción con el entorno.": "Study guide oriented to understand the elements, business rules and real contexts that exist outside the technical core of a system and that determine its correct functioning and interaction with the environment.",
    "Guía técnica centrada en el diseño, desarrollo y despliegue de aplicaciones web basadas en la arquitectura orientada a servicios (SOA) y microservicios, priorizando la escalabilidad y la comunicación eficiente entre sistemas.": "Technical guide focused on the design, development and deployment of web applications based on service-oriented architecture (SOA) and microservices, prioritizing scalability and efficient communication between systems.",
    "Guía de aprendizaje integral diseñada para fortalecer las cuatro habilidades lingüísticas (lectura, comprensión auditiva y expresión oral) en el idioma inglés, adaptada para el éxito en el entorno universitario y laboral multidisciplinario.": "Comprehensive learning guide designed to strengthen the four language skills (reading, listening, writing and speaking) in the English language, adapted for success in the university and multidisciplinary work environment.",
    
    // Syllabus topics
    "Plan Maestro de Producción (MPS)": "Master Production Schedule (MPS)",
    "Lista de Materiales (BOM)": "Bill of Materials (BOM)",
    "Demanda Dependiente": "Dependent Demand",
    "Requerimientos Netos": "Net Requirements",
    "Explosión de Materiales": "Explosion of Materials",
  },
};

export function getLanguage() {
  const saved = localStorage.getItem(LANG_KEY);
  return dictionary[saved] ? saved : "es";
}

export function applyLanguage(lang = getLanguage()) {
  if (!dictionary[lang]) lang = "es";
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[lang][key]) node.textContent = dictionary[lang][key];
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
    const key = node.dataset.i18nPlaceholder;
    if (dictionary[lang][key]) node.placeholder = dictionary[lang][key];
  });
  document.querySelectorAll("#languageToggle").forEach((button) => {
    button.textContent = lang.toUpperCase();
  });
}

export function initLanguage() {
  applyLanguage();
  document.querySelectorAll("#languageToggle").forEach((button) => {
    button.addEventListener("click", () => {
      const next = getLanguage() === "es" ? "en" : "es";
      localStorage.setItem(LANG_KEY, next);
      applyLanguage(next);
      // Disparar evento para que otros módulos sepan que cambió el idioma
      window.dispatchEvent(new Event("learnmore:language-change"));
    });
  });
}

export function translate(key, lang = getLanguage()) {
  if (!dictionary[lang]) lang = "es";
  return dictionary[lang][key] || key;
}

const TRANSLATION_ENDPOINTS = [
  "https://translate.argosopentech.com/translate",
  "https://translate.terraprint.co/translate",
  "https://lt.vern.cc/translate"
];

export async function translateDynamic(text, targetLang = getLanguage()) {
  if (!text) return text;
  
  if (dictionary[targetLang] && dictionary[targetLang][text]) {
    return dictionary[targetLang][text];
  }

  if (targetLang === "es") {
    return text;
  }

  // Loop through public LibreTranslate instances with failover
  for (const endpoint of TRANSLATION_ENDPOINTS) {
    try {
      const res = await fetch(endpoint, {
        method: "POST",
        body: JSON.stringify({
          q: text,
          source: "es",
          target: "en",
          format: "text"
        }),
        headers: {
          "Content-Type": "application/json"
        }
      });
      
      if (res.ok) {
        const data = await res.json();
        if (data && data.translatedText) {
          const translated = data.translatedText;
          if (!dictionary[targetLang]) dictionary[targetLang] = {};
          dictionary[targetLang][text] = translated;
          return translated;
        }
      }
    } catch (error) {
      console.warn(`Translation failed for endpoint ${endpoint}:`, error);
    }
  }

  return text;
}
