-- ===========================================================
-- MIGRACION INICIAL - LEARNMORE DATABASE SCHEMA
-- ===========================================================

-- ---------------------------------------------------------
-- Función: handle_updated_at
-- ---------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------
-- Tabla: careers
-- ---------------------------------------------------------

CREATE TABLE public.careers (
  id text NOT NULL,
  key text NOT NULL,
  name text NOT NULL,
  desc text,
  color text DEFAULT '#00d4ff',
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT careers_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_careers_key ON public.careers USING btree (key);
CREATE TRIGGER set_updated_at ON public.careers
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "careers_select_policy" ON public.careers FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "careers_insert_policy" ON public.careers FOR INSERT TO authenticated WITH CHECK (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "careers_update_policy" ON public.careers FOR UPDATE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "careers_delete_policy" ON public.careers FOR DELETE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));

-- ---------------------------------------------------------
-- Tabla: users
-- ---------------------------------------------------------

CREATE TABLE public.users (
  id text NOT NULL,
  email text NOT NULL,
  name text,
  role text NULL DEFAULT 'user'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users USING btree (role);
CREATE TRIGGER set_updated_at ON public.users
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users_select_policy" ON public.users FOR SELECT TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "users_insert_policy" ON public.users FOR INSERT TO authenticated, anon WITH CHECK (true);
CREATE POLICY "users_update_policy" ON public.users FOR UPDATE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "users_delete_policy" ON public.users FOR DELETE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));

-- ---------------------------------------------------------
-- Tabla: guides (EXISTING TABLE - BIGINT ID)
-- ---------------------------------------------------------

CREATE TABLE public.guides (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NULL,
  desc text NULL,
  sem bigint NULL,
  fileUrl text NULL,
  topics text[] NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  career text NULL,
  detail text NULL,
  views integer NULL DEFAULT 0,
  CONSTRAINT guides_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_guides_career ON public.guides USING btree (career);
CREATE INDEX IF NOT EXISTS idx_guides_sem ON public.guides USING btree (sem);
CREATE INDEX IF NOT EXISTS idx_guides_views ON public.guides USING btree (views DESC);
CREATE INDEX IF NOT EXISTS idx_guides_created_at ON public.guides USING btree (created_at DESC);
CREATE TRIGGER set_updated_at ON public.guides
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.guides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "guides_select_policy" ON public.guides FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "guides_insert_policy" ON public.guides FOR INSERT TO authenticated WITH CHECK (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "guides_update_policy" ON public.guides FOR UPDATE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "guides_delete_policy" ON public.guides FOR DELETE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "guides_views_increment_policy" ON public.guides FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- ---------------------------------------------------------
-- Tabla: messages
-- ---------------------------------------------------------

CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text NULL DEFAULT 'nuevo'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_messages_status ON public.messages USING btree (status);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages USING btree (created_at DESC);
CREATE TRIGGER set_updated_at ON public.messages
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "messages_select_policy" ON public.messages FOR SELECT TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "messages_insert_policy" ON public.messages FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "messages_update_policy" ON public.messages FOR UPDATE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "messages_delete_policy" ON public.messages FOR DELETE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));

-- ---------------------------------------------------------
-- Tabla: reviews
-- ---------------------------------------------------------

CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  name text NOT NULL,
  comment text NOT NULL,
  stars smallint NOT NULL,
  email text NULL,
  status text NULL DEFAULT 'nuevo'::text,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  reply text NULL,
  replied_at timestamp with time zone NULL,
  replied_by text NULL,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_stars_check CHECK (stars >= 1 AND stars <= 5)
);

CREATE INDEX IF NOT EXISTS idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON public.reviews USING btree (created_at DESC);
CREATE TRIGGER set_updated_at ON public.reviews
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reviews_insert_policy" ON public.reviews FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "reviews_select_policy" ON public.reviews FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "reviews_update_admin_policy" ON public.reviews FOR UPDATE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "reviews_delete_admin_policy" ON public.reviews FOR DELETE TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));

-- ---------------------------------------------------------
-- Tabla: activity
-- ---------------------------------------------------------

CREATE TABLE public.activity (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  type text,
  text text,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT activity_pkey PRIMARY KEY (id)
);

CREATE TRIGGER set_updated_at ON public.activity
  BEFORE UPDATE FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "activity_select_policy" ON public.activity FOR SELECT TO authenticated USING (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));
CREATE POLICY "activity_insert_policy" ON public.activity FOR INSERT TO authenticated WITH CHECK (auth.uid() IN (SELECT id FROM public.users WHERE role = 'admin'));

-- Insertar carreras por defecto
INSERT INTO public.careers (id, key, name, desc, color) VALUES
  ('mecatronica', '01', 'Mecatrónica', 'Carrera de Mecatrónica', '#00d4ff'),
  ('ti', '02', 'TI e Innovación Digital', 'Carrera de Tecnologías de la Información e Innovación Digital', '#7c3aed'),
  ('procesos', '03', 'Procesos Industriales', 'Carrera de Procesos Industriales', '#10b981')
ON CONFLICT (id) DO NOTHING;